//
// Created by Knight-ZXW on 2024/5/15.
//

#ifndef APPOPTIMIZEFRAMEWORK_KBART_SRC_MAIN_CPP_INCLUDE_BASE_VALUE_OBJECT_H_
#define APPOPTIMIZEFRAMEWORK_KBART_SRC_MAIN_CPP_INCLUDE_BASE_VALUE_OBJECT_H_
#include "macros.h"
namespace art {

class ValueObject {
 private:
    DISALLOW_ALLOCATION();
};

}  // namespace art
#endif //APPOPTIMIZEFRAMEWORK_KBART_SRC_MAIN_CPP_INCLUDE_BASE_VALUE_OBJECT_H_
